version: '3'

networks:
  bibbox-default-network:
    external: true
    
services:
  bibbox-moodle-mariadb:
    container_name: bibbox-moodle-mariadb
    image: bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_PASSWORD=bibbox
      - MARIADB_ROOT_PASSWORD=bibbox
    volumes:
      - ./data/mariadb_data/:/bitnami/mariadb/
    networks:
      - bibbox-default-network

  bibbox-moodle:
    container_name: bibbox-moodle
    image: bitnami/moodle:3.11.6
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=bibbox-moodle-mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bibbox
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_PASSWORD=bitnami
      - MOODLE_USERNAME=user
    volumes:
      - ./data/moodle_data:/bitnami/moodle
      - ./data/moodledata_data:/bitnami/moodledata
    depends_on:
      - bibbox-moodle-mariadb
    networks:
      - bibbox-default-network

